// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ooelorygkrwuejkcvefo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZWxvcnlna3J3dWVqa2N2ZWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwMjQ4NDMsImV4cCI6MjA5MzYwMDg0M30.eUpQfV15rae93DOuyuQL9IDcZYc7VfRKTC5vK50iyD4";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);